---

all:
  hosts:
    e1:
      ansible_host: 10.0.3.101
    e2:
      ansible_host: 10.0.3.102
    e3:
      ansible_host: 10.0.3.103
    pg1:
      ansible_host: 10.0.3.201
    pg2:
      ansible_host: 10.0.3.202
    pg3:
      ansible_host: 10.0.3.203
    backup:
      ansible_host: 10.0.3.204
  children:
    patroni_servers:
      hosts:
        pg1:
        pg2:
        pg3:
    etcd_servers:
      hosts:
        e1:
          ansible_host: 10.0.3.101
        e2:
          ansible_host: 10.0.3.102
        e3:
          ansible_host: 10.0.3.103
    backup_servers:
      hosts:
        backup:
    primary:
      hosts:
        pg1:
    secondary:
      hosts:
        pg2:
        pg3:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: "/usr/bin/python3"
    debian_codename: "bookworm"
    postgresql_version: "16"
    postgresql_instance: "main"
    ansible_distribution_release: "bookworm"
      


